services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

volumes:
  postgres-data: