services:
  postgres:
    container_name: postgres
    image: postgres:16.1-alpine
    environment:
      - POSTGRES_PASSWORD=test
    ports:
      - "5432:5432"
    networks:
      - sberbank-crud-network
    volumes:
      - "postgres-data:/var/lib/postgresql/data"

  sberbank-crud:
    container_name: sberbank-crud
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:8080"
    networks:
      - sberbank-crud-network
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/postgres
    depends_on:
      - postgres


volumes:
  postgres-data:

networks:
  sberbank-crud-network:
    driver: bridge
